version: '3'

services:
  mysql-master:
    image: essential_mysql5.7
    volumes:
      - ./master:/working
      - ./master_part:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=1234
    container_name: masterdb
    
  mysql-slave:
    image: essential_mysql5.7
    volumes:
      - ./slave_part:/var/lib/mysql
      - ./slave:/working
    depends_on:
      - mysql-master
    ports:
      - "3307:3307"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=1234
    container_name: slavedb
